#!/bin/bash
# 🚀 GUIDA SUPER-RAPIDA - SimpleEpochConverter

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 SimpleEpochConverter - Comandi Essenziali"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 BUILD & TEST"
echo "  ./build.sh              # Compila l'app"
echo "  ./run.sh                # Esegue l'app"
echo "  ./manage.sh test        # Build + run completo"
echo "  ./manage.sh verify      # Verifica tutto ok"
echo ""
echo "🔧 GESTIONE APP"
echo "  ./manage.sh status      # Stato app"
echo "  ./manage.sh restart     # Riavvia app"
echo "  ./manage.sh stop        # Ferma app"
echo "  ./manage.sh logs        # Vedi log"
echo ""
echo "📤 UPLOAD GITHUB"
echo "  ./github-setup.sh       # Setup automatico GitHub"
echo "                          # (gestisce anche repo già inizializzati!)"
echo ""
echo "📚 DOCUMENTAZIONE"
echo "  cat QUICK_START.md      # Guida rapida"
echo "  cat GITHUB_QUICK.md     # GitHub in 5 minuti"
echo "  cat INDEX.md            # Indice completo"
echo "  ./manage.sh help        # Aiuto script"
echo ""
echo "✅ STATO PROGETTO"
echo "  ✓ Compilazione funzionante"
echo "  ✓ Tutti gli script OK"
echo "  ✓ Documentazione completa"
echo "  ✓ Pronto per GitHub"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
